name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    name: Update Dependencies
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Update Maven dependencies
      run: |
        cd app
        ./mvnw versions:update-properties
        ./mvnw versions:use-latest-versions
        
    - name: Update GitHub Actions
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          This is an automated pull request to update dependencies.
          
          Please review the changes and ensure all tests pass before merging.
          
          - Maven dependencies updated to latest versions
          - GitHub Actions updated to latest versions
        branch: dependency-updates
        delete-branch: true
        
  security-audit:
    runs-on: ubuntu-latest
    name: Security Audit
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Run OWASP Dependency Check
      run: |
        cd app
        ./mvnw org.owasp:dependency-check-maven:check
        
    - name: Upload dependency check report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: dependency-check-report
        path: app/target/dependency-check-report.html
